# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and lint applications

on:
  push:
    branches: [main, static-analysis, github-actions]
  pull_request:
    branches: [main, static-analysis] # currently

jobs:
  test:
    name: Test and lint-checks for application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install
      - name: type checking
        run: yarn type-check
      - name: Check linting
        run: yarn lint --max-warnings=0
      - name: Check format
        run: yarn format-check
      - name: Test application
        run: yarn test
