# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, static-analysis, github-actions]
  pull_request:
    branches: [main, static-analysis] # currently

jobs:
  build:
    name: Build application
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Setup ${{ matrix.node-version }} and ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - name: Build application
        run: yarn build
      - name: Package application (Linux, Mac)
        if: runner.os != 'Windows'
        run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn dist
      - name: Package application (Windows)
        if: runner.os == 'Windows'
        run: |
          set GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          yarn dist
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-node${{ matrix.node-version }}
          path: dist

  test:
    name: Test and lint-checks for application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install
      - name: Check linting and format
        run: yarn lint
      - run: yarn format-check
      - name: Test application
        run: yarn test
